x=int(input("x:"))
y=int(input("y:"))
print("x+y=",x+y)
print("x*y=",x*y)
print("x/y=",x/y)
print("x-y=",x-y)
print("x^y=",x**y)
print("x//y=",x//y)
print("x%y=",x%y)

print("x%2+2x+1",x**2+2*x+1)
print("x%2+2xy+y",x**2+2*x*y+y)
